default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: uv run pyupgrade --py310-plus
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        entry: uv run ruff check --fix --settings-path pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: ruff-fmt
        name: ruff-fmt
        entry: uv run ruff format --check --settings-path pyproject.toml
        types: [python]
        language: system
