[build-system]
requires = ["maturin>=1.15,<2.0"]
build-backend = "maturin"

[project]
name = "adaptif"
version = "0.2.0"
description = "Python implementation of DSP adaptive filters"
readme = "README.md"
authors = [
    { name = "bglid", email = "benjamin.h.glidden@gmail.com" }
]
license="MIT OR Apache-2.0"
license-files = ["LICENSE-APACHE", "LICENSE-MIT"]
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.21.0,<2.0.0",
]
classifiers = [  
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/bglid/adaptive-filters"
Repository = "https://github.com/bglid/adaptive-filters"


[dependency-groups]
dev = [
    "bandit>=1.7.1,<2.0.0",
    "pre-commit>=4.0.1,<5.0.0",
    "pytest>=9.1.1",
    "safety>=2.2.0",
    "pytest-cov>=6.0.0,<7.0.0",
    "ruff>=0.16.4",
    "ty>=0.0.75",
    "maturin>=1.15.0",
]

[tool.maturin]
bindings = "pyo3"
features = ["python"]

[tool.ruff]
target-version = "py310"
exclude = [
    "env",
    "src/*", # Rust code
]

[tool.ruff.lint]
extend-select = ["I", "B", "DOC"]
preview = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ty.src]
include = [
    "adaptive_filter",
    "adaptif",
    "tests",
]

[tool.pytest.ini_options]
# https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml
# Directories that are not visited by pytest collector:
norecursedirs =["hooks", "*.egg", ".eggs", "dist", "build", "docs", ".tox", ".git", "__pycache__"]
doctest_optionflags = ["NUMBER", "NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL"]

# Extra options:
addopts = [
  "--strict-markers",
  "--tb=short",
  "--doctest-modules",
  "--doctest-continue-on-failure",
]

[tool.coverage.run]
source = ["adaptive_filter"]
branch = true

[tool.coverage.paths]
source = ["adaptive_filter"]

[tool.coverage.report]
fail_under = 50
show_missing = true
