from numpy.typing import NDArray

class LMSFilter:
    def __init__(self, mu: float, window_size: int) -> None: ...
    @property
    def window_size(self) -> int: ...
    def adapt(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...
    def filter(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...
